#!/bin/bash

# NOTE: This file contains "secrets". None of these secrets in this file 
# are critical Imaginea secrets - they're just random numbers - but users
# of this project are expected to keep their secrets safe.

# Use your own GAUTH ids here. These are fake.
export INAI_GAUTH_CLIENT=123456781234-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com
export INAI_GAUTH_AUDIENCE1=123456781234-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com
export INAI_GAUTH_AUDIENCE2=123456781234-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com
export INAI_GAUTH_AUDIENCE3=123456781234-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com

# Use your own ThumbSignIn ids here. These are fake.
export INAI_THUMBSIGNIN_ACCESSKEYID=0123456789abcdef0123456789abcdef
export INAI_THUMBSIGNIN_SECRETKEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

# These are produced by random number generators. Make your own.
export INAI_AUTH_BROWSER_ID=383289e466a4089e29cb
export INAI_AUTH_BROWSER_SECRET=de2c430f5ede0f4ce381af89af03227b75a1a9df
export INAI_AUTH_SERVER_ID=d0cf803d412e2631c3f2
export INAI_AUTH_SERVER_SECRET=8a4d08d231758b0e9cb1adb31e451f7d4e99a3c2
export INAI_AUTH_ADMIN_ID=4c8f951af0b1e868ea87
export INAI_AUTH_ADMIN_SECRET=f59872a504a76df60b72a320592363303aea9b8c
export INAI_AUTH_SYSTEM_ID=233908a1e0b607667243
export INAI_AUTH_SYSTEM_SECRET=836127f789deb3ee956e5e8a39b3d2068cf07796

# These are produced by random number generators. Make your own.
export INAI_APP_ID=383289e466a4089e29cb
export INAI_APP_SECRET=de2c430f5ede0f4ce381af89af03227b75a1a9df

node $1 src/server.js
